### ISSUE TITLE
Umatched bracket not highlighted

### ISSUE THREAD

**Issue by nitanagdeote** [vizhub-core/vzcode#637]
![image](https://github.com/vizhub-core/vzcode/assets/13540669/b3b05b97-3558-4247-9056-c4902a71a45b)

As a user editing code, I want to know when a starting bracket (paren, bracket, brace, etc) does not have a corresponding ending bracket, so that it's easier to identify the syntax error and steps to fix it.

VSCode has this feature (see screenshot above)

![image](https://github.com/vizhub-core/vzcode/assets/13540669/d454dd1f-6a59-4585-b144-95669c874d0a)

VZCode does not - it shows the ending syntax error but does not highlight the starting bracket.

**Comment by curran** [comment]
It's possible we can make this work by simply adding CSS that targets `.codemirror-nonmatching-bracket`.

**Comment by curran** [comment]
There are `cm-matchingBracket` and `cm-nonmatchingBracket` classes, and they are already styled.

This is the non-matching style, which is unfortunately only highlighted when the cursor is next to that character (otherwise it doesn't even get that `cm-nonmatchingBracket` class unfortunately).

![image](https://github.com/vizhub-core/vzcode/assets/68416/5d8f77c3-224c-49b7-bcb8-f9c80c77e420)

I researched this a bit and found:

 * [Adding an option to always highlight unmatched brackets](https://discuss.codemirror.net/t/adding-an-option-to-always-highlight-unmatched-brackets/656) According to the author of CodeMirror, this is not a feature that is supported or planned
 * [Always highlight unmatching brackets](https://discuss.codemirror.net/t/always-highlight-unmatching-brackets/6881) - also flagged as unsupported

However, there is another idea which is "Rainbox brackets"

 * [Bracket Pair Colorization in cm6?](https://discuss.codemirror.net/t/bracket-pair-colorization-in-cm6/5656)
 * https://github.com/eriknewland/rainbowbrackets

I think what I can do with this is just make the styling for matching and unmatched backets more visible. It does not seem feasible to always highlight the non-matching brackets like VSCode does.

**Comment by curran** [comment]
From ChatGPT:

```js
import { tags as t } from '@lezer/highlight';
import { createTheme } from '@uiw/codemirror-themes';

import {
  // Define colors for matching and non-matching brackets
  matchingBracketColor,
  nonMatchingBracketColor,

  // Other colors...
} from './colors';

const defaultSettingsVizhubTheme = {
  // Default settings...
};

function vizhubThemeInit(options) {
  const { styles = [], ...otherOptions } = options || {};
  return createTheme({
    ...otherOptions,
    styles: [
      // Other styles...
      {
        tag: t.matchingBracket,
        color: matchingBracketColor,
        backgroundColor: 'transparent', // Optional: set background color for matching brackets
      },
      {
        tag: t.nonmatchingBracket,
        color: nonMatchingBracketColor,
        backgroundColor: 'transparent', // Optional: set background color for non-matching brackets
      },
      ...styles,
    ],
  });
}

export const vizhubTheme = vizhubThemeInit();


```
