### ISSUE TITLE
Drop down menus not working

### ISSUE THREAD

**Issue by nitanagdeote** [vizhub-core/vzcode#662]
Sort by option and Resources drop-down need to be fixed.

**Comment by curran** [comment]
Yeah this is sort of a scary bug that I and others noticed as well. I'm not sure exactly what is happening, but it seems to happen when the server memory usage gets high. My theory is that somehow a JavaScript chunk gets cut off or something, so we are not loading all the code that powers the interactions.

To address this, I added a new policy to the server to have it auto-restart when memory usage crosses a certain threshold. This should make it so that this issue of the drop downs not working should (fingers crossed) not happen again. This feels like a band-aid though, as there must be a memory leak somewhere that is causing the memory to overrun.

Closing for now as I believe this is solved. Thanks for reporting!
