### ISSUE TITLE
Connection Lost Notification

### ISSUE THREAD

**Issue by jeffrey-asm** [vizhub-core/vzcode#827]
The current behavior is that when the connection is lost to the server, the connection status is updated on the sidebar, but this is too subtle. A popup notification would be more user-friendly, especially if several changes are made without noticing this connection loss.

<img width="525" alt="image" src="https://github.com/user-attachments/assets/3960e5b8-b38c-42bc-ab86-420f73c3204a">

**Comment by curran** [comment]
Closing this one as I don't think it needs to have such high prominence.

The reason is that sometimes the connection is in fact lost and then re-established, and this happens "normally" all the time, just because of the way that the VizHub servers are deployed. They use AWS ECS with horizontal scaling, and there appears to be some sort of timeout for WebSocket connections, which I don't see any way around. So in the meantime, unless that changes, I would prefer to keep it subtle, so we don't interrupt the user randomly every time it happens. The unsaved local changes will get saved properly as soon as the reconnection happens, which is automatic.

Thanks, though, for the idea!
